{
 "title": "Kafka Overview with Burrow consumer lag stats",
 "description": "Kafka resource usage and consumer lag overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Cores" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kafka-hs\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "sum by (pod_name)(container_memory_usage_bytes{pod_name=~\"kafka-.\"}) ",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Time spent in GC",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit", "label": "% time in GC" }
   ],
   "targets": [
    {
     "expr": "sum without(gc)(rate(jvm_gc_collection_seconds_sum{job=\"kafka-hs\"}[5m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka-hs\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka-hs\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance, pod)(rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka-hs\",topic!=\"\"}[5m]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "grips-na-raw offset (How fast offset increases)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by(topic)(rate(kafka_log_logendoffset{ topic = \"grips-na-raw\" }[10m]))",
     "legendFormat": "speed {{topic}}"
    },
    {
     "expr": "sum by(topic)(kafka_log_logendoffset{ topic = \"grips-na-raw\" })",
     "legendFormat": "count {{topic}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_burrow_total_lag", "legendFormat": "{{group}}" }
   ]
  },
  {
   "title": "Average partition lag by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (group)(rate(kafka_burrow_partition_lag[10m]))",
     "legendFormat": "{{group}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (topic)(kafka_cluster_partition_underreplicated)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_server_replicamanager_isrexpands_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Offline partitions",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_controller_kafkacontroller_offlinepartitionscount",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}